#!/bin/bash

# Update lib for GNU ld scripts
# Assumes that the binary is the first indicated in whereis,
# with the ld script being of type "ASCII text", with the
# first file reference after "GROUP"

# depends on: whereis, sed, file, grep, basename

# BSD licence
# Mark Clements <mark.clements@ki.se> 2021-05-07

shortname () {
    echo -n $(basename $1 | sed -n 's/^lib\(.*\)[.][aso]/\1/p')' '
}
processArg () {
    # remove the -l prefix and define libname
    libname=$(echo $1 | sed -n 's/[-]l\(.*\)/lib\1.so/p')
    if [ -n "$libname" ]
    then
	# extract the *first* library in whereis
	fullname=$(whereis -b $libname | sed -n 's/[^ :]*[:] \([^ ]*\).*/\1/p')
	if [ -e $fullname ]
	then
	    if [ "$(file -b $fullname)"="ASCII text" ]
	    then
		# extract the filenames after GROUP
		lst=( $(sed -n 's/^GROUP *[(] *\([^)]*\) *.*/\1/p' $fullname) )
		if [ -n "$lst" ]
		then
		    for j in ${lst[@]}; do
			echo -n -l$(shortname $j)' '
		    done
		    exit
		fi
	    fi
	fi
    fi
    # if fails somewhere then return the origin input
    echo -n $1' '
}
args=$*
for i in ${args[@]}; do
    echo -n $(processArg $i)' '
done
